### ISSUE TITLE
Add to Queue display order

### ISSUE THREAD

**Issue by mark-walle** [bcgov/sbc-qsystem#172]
Currently queue order appears to be alphabetical on Service, instead of in the expected priority queue determined sequence:
- suppress listbox component sorting option (ZKoss),
- force appearance on queue priority,
- fix queue sequence on redirected clients -- this is a deeper bug than the display.

**Comment by gil0109** [comment]
Confirmed Resolved with UI update, sort algorithm added, comments translation, version number… #185
