### ISSUE TITLE
Service BC Queuing System - Technical Lead

### ISSUE THREAD

**Issue by ccoldwell** [bcgov/sbc-qsystem#175]
Value: $12,000.00Closes: 23:00 PST, Wednesday, October 18, 2017Location: Victoria In-person work NOT required<h2>Opportunity Description</h2><h3 dir="ltr" style="line-height: 1.38; margin-top: 16pt; margin-bottom: 4pt;"><span style="font-size: 13pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Background</span></h3>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><span style="box-sizing: border-box; font-weight: 400; background-color: transparent; font-size: 11pt; vertical-align: baseline;">We have been experimenting with an open-source queue management system (</span><a style="box-sizing: border-box; text-decoration-line: none; transition: all 0.35s; color: #009acf; font-family: 'Open Sans', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; white-space: normal;" href="https://bitbucket.org/Apertum/qsystem"><span style="box-sizing: border-box; font-size: 11pt; font-family: Arial; color: #1155cc; background-color: transparent; text-decoration-line: underline; vertical-align: baseline; white-space: pre-wrap;">QSystem</span></a><span style="box-sizing: border-box; font-weight: 400; background-color: transparent; font-size: 11pt; vertical-align: baseline;">) with the hope of adapting it for the </span><a style="box-sizing: border-box; text-decoration-line: none; transition: all 0.35s; color: #009acf; font-family: 'Open Sans', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; white-space: normal;" href="http://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc"><span style="box-sizing: border-box; font-size: 11pt; font-family: Arial; color: #1155cc; background-color: transparent; text-decoration-line: underline; vertical-align: baseline; white-space: pre-wrap;">Service BC</span></a><span style="box-sizing: border-box; font-weight: 400; background-color: transparent; font-size: 11pt; vertical-align: baseline;"> offices across the province of British Columbia. So far, we&rsquo;ve made some enhancments and piloted the system in three offices with some good results. Our end goal is to continue adapting the product and our infrastructure so that we can successfully roll it out to all 62 offices and sustain it! Our </span></span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;">modified code can be found </span><a style="text-decoration-line: none;" href="https://github.com/bcgov/sbc-qsystem"><span style="font-size: 11pt; font-family: Arial; color: #1155cc; background-color: transparent; text-decoration-line: underline; vertical-align: baseline; white-space: pre-wrap;">here</span></a><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Through the pilot, we&rsquo;ve discovered the next improvements we need to make, and scoped that out into three phases of work:</span></p>
<p><strong style="font-weight: normal;">&nbsp;</strong></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-indent: 36pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Phase 1 - Multi-Tenant model</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; margin-left: 36pt;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Desired Output: Change the underlying architecture of the application so that it can support a multi-tenant model </span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; margin-left: 36pt;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Target dates: Oct 12 - Nov 9, 2017</span></p>
</li>
</ul>
<p><strong style="font-weight: normal;">&nbsp;</strong></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; margin-left: 36pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Phase 2 - Software Development</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; margin-left: 36pt;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Desired Output: Pre-release load testing and performance improvements</span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; margin-left: 36pt;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Target dates: Nov 9 - Dec 29, 2017</span></p>
</li>
</ul>
<p><strong style="font-weight: normal;">&nbsp;</strong></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; margin-left: 36pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Phase 3 - Refactoring of technical debt</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; margin-left: 36pt;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Desired Output: Improvements in security and further system performance</span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; margin-left: 36pt;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Target dates: Jan 2 - 31, 2018</span></p>
</li>
</ul>
<h3 dir="ltr" style="line-height: 1.38; margin-top: 16pt; margin-bottom: 4pt;"><span style="font-size: 13pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Opportunity</span></h3>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">This opportunity is to act as our </span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">technical lead </span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">through these three phases of work, working in concert with the successful applicant we assign to work as the software developer (see <a href="opp-service-bc-queuing-system---software-developer">this opportunity</a>).</span></p>
<p><strong style="font-weight: normal;">&nbsp;</strong></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The fixed-price reward is for a total of </span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">$12,000*</span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> for fulfilling the </span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Acceptance Criteria</span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> below, per this payment schedule:</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Completion of Phase 1 - $4,600</span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Completion of Phase 2 - $4,100 </span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Completion of Phase 3 - $3,300</span></p>
</li>
</ul>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">*The full amount is dependent on an evaluation of outputs at the end of Phase 1, during which Service BC will determine whether or not work will continue into phases 2 and 3.</span></p><h2>Acceptance Criteria</h2><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<ol style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Provide the Government program area code acceptance recommendations for phases 1-3:</span></p>
</li>
<ol style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: lower-alpha; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Update the repo approval-log (via a pull request).</span></p>
</li>
<li dir="ltr" style="list-style-type: lower-alpha; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Ensure that the code delivered by the software developer has been functionally tested.</span></p>
</li>
<li dir="ltr" style="list-style-type: lower-alpha; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Ensure that the code delivered by the developer has been reviewed for quality via SonarQube.</span></p>
</li>
<li dir="ltr" style="list-style-type: lower-alpha; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Review and accept/reject pull requests from the developer (per requirements of criteria 3-5).</span></p>
</li>
</ol>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Deliver to Service BC:</span></p>
</li>
<ol style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: lower-alpha; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Detailed documentation of the work done by the developer.</span></p>
</li>
<li dir="ltr" style="list-style-type: lower-alpha; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Records that demonstrate the trend of code quality.</span></p>
</li>
</ol>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Provide technical leadership and advice to the software developer.</span></p>
</li>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Work with Service BC staff and the software developer to plan and execute the production release of the software.</span></p>
</li>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Maintain frequent communication with Service BC technical staff to transfer your knowledge and update on progress of the software developer.</span></p>
</li>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;"><span style="white-space: pre-wrap;">The successful candidate can not be the same as </span>the software developer (see <a style="font-size: 14.6667px; white-space: pre-wrap;" href="opp-service-bc-queuing-system---software-developer">this opportunity</a><span style="font-size: 14.6667px; white-space: pre-wrap;">).</span></li>
</ol><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-service-bc-queuing-system---technical-lead">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on 23:00 PST, Wednesday, October 18, 2017</b>.</p><p>We plan to assign this opportunity by <b>Monday, October 23, 2017</b> with work to start on <b>Thursday, October 26, 2017</b>.</p><p>If your proposal is accepted and you are assigned to the opportunity, you will be notified by email and asked to confirm your agreement to the <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf"><i>Code With Us</i> terms and contract.</a></p><h2>Proposal Evaluation Criteria</h2><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<ol style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your prior experience with converting applications from single-tenant to multi-tenant, and releasing production applications (prior experience working with the public sector would be an asset) (30 points).</span></p>
</li>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Experience with/knowledge of OpenShift, Docker, and/or other container based systems (20 points).</span></li>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your expertise in Java and experience contributing Java code to public code repositories (10 points).</span></p>
</li>
<li dir="ltr" style="list-style-type: decimal; font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;">Your ability to satisfy the Acceptance Criteria on or before [</span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: #fff2cc; vertical-align: baseline; white-space: pre-wrap;">31 January, 2018</span><span style="font-size: 11pt; font-family: Arial; color: #434343; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;">] (10 points).</span></p>
</li>
</ol>

**Comment by gil0109** [comment]
Hi folks, I am the lead opportunity contact for this issue.  Please post any questions you have here and we'll do our best to respond promptly.

**Comment by gil0109** [comment]
Hi folks, I have re-opened this opportunity.     We are looking for someone to provide technical advice and guidance to the team developing the multi tenant solution.  Also, this person will provide a quality assurance assessment on the code.  Please let me know if you have any questions.  

Any comments and/or suggestions are welcome.

**Comment by richkallan** [comment]
Are we able to bid a maximum # of ours for this engagement.  In essence timeboxing the engagement to reduce our risk?

**Comment by richkallan** [comment]
Also are there extra points available to companies who can demonstrate depth and capacity in the way they resource this (and other similar) engagements?

**Comment by gil0109** [comment]
Hi richkallan,

Based on  your question (I have adjusted it):  "Are we able to bid a maximum # of **hours** for this engagement. In essence timeboxing the engagement to reduce our risk?"

Response:  Absolutely.  This is an open competition.  So please place your restrictions within your proposal.  We will assess them based on the Proposal Evaluation Criteria.  This may cause a reduction of  the points in this evaluation for item 4.

Regards,
Karim

**Comment by richkallan** [comment]
Ok thanks Karim.  Appreciate the quick response.

Rich.

**Comment by gil0109** [comment]
Hi richkallan,

In regards to your question "Also are there extra points available to companies who can demonstrate depth and capacity in the way they resource this (and other similar) engagements?"

Response: The points given are outlined in our evaluation criteria. Depth and capacity can be a way to demonstrate the ability to meet the criteria and outcomes we are looking for.

**Comment by gil0109** [comment]
Closed with no proponent chosen.
