### ISSUE TITLE
Customer Flow Management System (CFMS) Modernization

### ISSUE THREAD

**Issue by ccoldwell** [bcgov/sbc-qsystem#325]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/cwu/opp-qsystem-replacement---redevelopment">opportunity page</a> and submit a proposal before Thursday, May 3, 2018</p>

**Comment by gil0109** [comment]
Hi folks, I am the lead opportunity contact for this issue. Please post any questions you have here and we'll do our best to respond promptly.

**Comment by MarcinZaranski** [comment]
Hi. I'm wondering if the work anticipates a single developer, or should include project management and peer reviews of the code. The allocated amount for this project looks insufficient to accommodate anything beyond straight development.

**Comment by gil0109** [comment]
@MarcinZaranski, Thank you for your feedback, we appreciate the insight.  We are open to proposals from a team or single full stack developer.  Our expectation is that the team or single person would use internal processes to ensure the phases are complete and delivered on time.   The candidate would have support from our internal developer for peer reviews and the Innovation lab for help with building the OpenShift Templates.
 
If you require additional support from the internal Government teams, please add them as assumptions to your proposal.

**Comment by StephenOTT** [comment]
@gil0109  how did you eval/determine the pricing for each phase?

**Comment by gil0109** [comment]
@StephenOTT, Yes, using Openshift, we will need to test and ensure the sample code is persistent through an openshift patching event,  That is moving the pod from one node to another.  

For example, if the sample code add's a simple item to a queue and displays the queue for multiple users.

We could do load testing to ensure we can scale to multiple containers.

And more importantly, We would add a couple of items.  We would have a few containers, rebuild the container and move them between nodes to ensure:
1. The application doesn't crash and is stable between the move
2. The the user is still logged on and the displays the same list and adding another item after the move 
3.  Ensure the user can still add additional items after the move

I hope this helps.

**Comment by gil0109** [comment]
Question and responsea from anonymous:

Question: There is no end-point for create customer. I think this was just an oversight?
Answer: This is included in End Point 7: Update Customer data.   This includes things like create customer, remove customer, returning to the queue, or placing on hold, Also note: Citizen left, complete service, or inaccurate time are special cases of the general "remove customer" requirement.

Of course, if you feel this should be separated for efficiency or other valid reasons, we are happy to discuss and change this, if it makes sense.

**Comment by mrgeorgephilip** [comment]
I was planning to propose a team. Is there a way to submit the resumes of each team member?

**Comment by gil0109** [comment]
This Code with us has been complete and the new Github repository: https://github.com/bcgov/queue-management has the new code base. 

As such, this repository will now be archived.
